import fs from 'fs';
import path from 'path';
import { getRelevantFacts, formatFactsForPrompt } from './fact-extractor.js';

const MEMORY_DIR = '.pangkas';
const MEMORY_FILE = 'memory.json';
const CONTEXT_FILE = 'CONTEXT.md';

function getMemoryDir(projectRoot) {
  return path.join(projectRoot, MEMORY_DIR);
}

function getMemoryPath(projectRoot) {
  return path.join(projectRoot, MEMORY_DIR, MEMORY_FILE);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ==========================================
// v2.0: Fact-based Memory
// ==========================================

/**
 * Load memory v2.0 (fact-based)
 * Returns null if file doesn't exist or is v1.x format
 */
export function loadMemory(projectRoot) {
  const filepath = getMemoryPath(projectRoot);
  try {
    const raw = fs.readFileSync(filepath, 'utf8');
    const data = JSON.parse(raw);
    
    // Handle v1.x migration — ignore old format
    if (!data.version || data.version !== '2.0') {
      return null;
    }
    
    return data;
  } catch {
    return null;
  }
}

/**
 * Save facts to memory v2.0
 */
export function saveFacts(projectRoot, facts) {
  const dir = getMemoryDir(projectRoot);
  ensureDir(dir);
  ensureGitignore(projectRoot);
  
  const filepath = getMemoryPath(projectRoot);
  const payload = {
    version: '2.0',
    lastUpdated: new Date().toISOString(),
    projectRoot,
    facts: facts || [],
  };
  
  fs.writeFileSync(filepath, JSON.stringify(payload, null, 2));
  updateContextMarkdown(projectRoot, payload);
}

/**
 * Get formatted facts for injection into system prompt
 */
export function getFactsForInjection(projectRoot, options = {}) {
  const memory = loadMemory(projectRoot);
  if (!memory || !memory.facts || memory.facts.length === 0) {
    return null;
  }
  
  const relevant = getRelevantFacts(memory.facts, options);
  if (relevant.length === 0) return null;
  
  return formatFactsForPrompt(relevant);
}

/**
 * Get raw facts array (for dashboard, etc.)
 */
export function getAllFacts(projectRoot) {
  const memory = loadMemory(projectRoot);
  return memory?.facts || [];
}

// ==========================================
// v1.x: Legacy Support (deprecated)
// ==========================================

/**
 * @deprecated Use saveFacts() instead
 */
export function saveMemory(projectRoot, data) {
  console.warn('[Pangkas] saveMemory() is deprecated. Use saveFacts() instead.');
  
  // Convert old format to facts if possible
  const facts = [];
  if (data.sessionSummary) {
    facts.push({
      id: 'legacy-' + Date.now(),
      type: 'decision',
      content: data.sessionSummary.slice(0, 150),
      confidence: 0.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      sessionCount: 1,
      isLatest: true,
    });
  }
  if (data.recentFocus && data.recentFocus !== data.sessionSummary) {
    facts.push({
      id: 'legacy-focus-' + Date.now(),
      type: 'todo',
      content: data.recentFocus.slice(0, 150),
      confidence: 0.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      sessionCount: 1,
      isLatest: true,
    });
  }
  if (Array.isArray(data.keyDecisions)) {
    for (const d of data.keyDecisions) {
      facts.push({
        id: 'legacy-decision-' + Date.now() + '-' + Math.random().toString(36).slice(2, 7),
        type: 'decision',
        content: d.slice(0, 150),
        confidence: 0.8,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sessionCount: 1,
        isLatest: true,
      });
    }
  }
  if (Array.isArray(data.filesModified)) {
    for (const f of data.filesModified) {
      facts.push({
        id: 'legacy-file-' + Date.now() + '-' + Math.random().toString(36).slice(2, 7),
        type: 'file',
        content: f,
        confidence: 0.9,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sessionCount: 1,
        isLatest: true,
      });
    }
  }
  
  saveFacts(projectRoot, facts);
}

/**
 * @deprecated Use saveFacts() instead
 */
export function updateMemory(projectRoot, patch) {
  console.warn('[Pangkas] updateMemory() is deprecated. Use saveFacts() instead.');
  saveMemory(projectRoot, patch);
}

// ==========================================
// Shared Utilities
// ==========================================

export function updateContextMarkdown(projectRoot, data) {
  const dir = getMemoryDir(projectRoot);
  ensureDir(dir);
  const mdPath = path.join(dir, CONTEXT_FILE);
  
  const lines = [
    '# Pangkas Session Context',
    '',
    `> Auto-generated by Pangkas. Last updated: ${data.lastUpdated || new Date().toISOString()}`,
    '',
  ];
  
  // v2.0 format: show facts grouped by type
  if (data.version === '2.0' && Array.isArray(data.facts)) {
    const activeFacts = data.facts.filter(f => f.isLatest);
    
    if (activeFacts.length === 0) {
      lines.push('No active facts recorded yet.');
    } else {
      // Group by type
      const grouped = {};
      for (const f of activeFacts) {
        if (!grouped[f.type]) grouped[f.type] = [];
        grouped[f.type].push(f);
      }
      
      const typeOrder = ['bug', 'todo', 'decision', 'preference', 'question', 'file', 'done'];
      for (const type of typeOrder) {
        if (!grouped[type]) continue;
        lines.push(`## ${type.toUpperCase()} (${grouped[type].length})`);
        for (const f of grouped[type]) {
          const confidence = f.confidence > 0.8 ? ' ★' : '';
          lines.push(`- ${f.content}${confidence}`);
        }
        lines.push('');
      }
    }
  } else {
    // v1.x fallback
    lines.push('## Current Focus');
    lines.push(data.recentFocus || 'N/A');
    lines.push('');
    lines.push('## Recent Session Summary');
    lines.push(data.sessionSummary || 'N/A');
  }
  
  fs.writeFileSync(mdPath, lines.join('\n'));
}

export function ensureGitignore(projectRoot) {
  const gitignorePath = path.join(projectRoot, '.gitignore');
  const entry = '.pangkas/';
  let content = '';
  try {
    content = fs.readFileSync(gitignorePath, 'utf8');
  } catch {
    // file does not exist
  }
  if (content.includes(entry)) return;
  const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
  fs.writeFileSync(gitignorePath, `${content}${separator}${entry}\n`);
}
