import fs from 'fs';
import path from 'path';

const MEMORY_DIR = '.pangkas';
const MEMORY_FILE = 'memory.json';
const CONTEXT_FILE = 'CONTEXT.md';

function getMemoryDir(projectRoot) {
  return path.join(projectRoot, MEMORY_DIR);
}

function getMemoryPath(projectRoot) {
  return path.join(projectRoot, MEMORY_DIR, MEMORY_FILE);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

export function loadMemory(projectRoot) {
  const filepath = getMemoryPath(projectRoot);
  try {
    const raw = fs.readFileSync(filepath, 'utf8');
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function saveMemory(projectRoot, data) {
  const dir = getMemoryDir(projectRoot);
  ensureDir(dir);
  ensureGitignore(projectRoot);
  const filepath = getMemoryPath(projectRoot);
  const payload = {
    version: '1.0',
    lastUpdated: new Date().toISOString(),
    projectRoot,
    ...data,
  };
  fs.writeFileSync(filepath, JSON.stringify(payload, null, 2));
  updateContextMarkdown(projectRoot, payload);
}

export function updateMemory(projectRoot, patch) {
  const existing = loadMemory(projectRoot) || {};
  const merged = { ...existing, ...patch, lastUpdated: new Date().toISOString() };
  saveMemory(projectRoot, merged);
}

export function updateContextMarkdown(projectRoot, data) {
  const dir = getMemoryDir(projectRoot);
  ensureDir(dir);
  const mdPath = path.join(dir, CONTEXT_FILE);
  const lines = [
    '# Pangkas Session Context',
    '',
    `> Auto-generated by Pangkas. Last updated: ${data.lastUpdated || new Date().toISOString()}`,
    '',
    '## Current Focus',
    data.recentFocus || 'N/A',
    '',
    '## Recent Session Summary',
    data.sessionSummary || 'N/A',
    '',
    '## Key Decisions',
  ];
  const decisions = Array.isArray(data.keyDecisions) ? data.keyDecisions : [];
  if (decisions.length === 0) {
    lines.push('- None yet');
  } else {
    for (const d of decisions) {
      lines.push(`- ${d}`);
    }
  }
  lines.push('');
  lines.push('## Files Being Modified');
  const files = Array.isArray(data.filesModified) ? data.filesModified : [];
  if (files.length === 0) {
    lines.push('- N/A');
  } else {
    for (const f of files) {
      lines.push(`- \`${f}\``);
    }
  }
  lines.push('');
  fs.writeFileSync(mdPath, lines.join('\n'));
}

export function ensureGitignore(projectRoot) {
  const gitignorePath = path.join(projectRoot, '.gitignore');
  const entry = '.pangkas/';
  let content = '';
  try {
    content = fs.readFileSync(gitignorePath, 'utf8');
  } catch {
    // file does not exist
  }
  if (content.includes(entry)) return;
  const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
  fs.writeFileSync(gitignorePath, `${content}${separator}${entry}\n`);
}
